# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "ironswing" do

pod 'AFNetworking', '~> 2.4'
pod 'SDWebImage', '~>3.6'

end

target "ironswingTests" do

end

